### ISSUE TITLE
Steam fullscreen game capture

### ISSUE THREAD

**Issue by luncht1me** [WatchBeam/obs-studio-ftl#16]
Hey guys, I built obs-ftl yesterday and it works GREAT, I love being able to do 60fps over FTL...

But, I'm unable to capture fullscreen steam games like CSGO with the 'game capture'. Both Tachyon and regular OBS capture CSGO fullscreen, but OBS-FTL will not. I can have all 3 programs open and CSGO will capture on every one except OBS-FTL.

Games that are in a 'psuedo-fullscreen' mode will capture w/ 'window capture', so there's something a little broken here, maybe the direct draw or dx capture dlls that are bundled to compile the software with?

I used the dependencies supplied in the readme, using VS2015 64bit.

**Comment by Maximilian-Reuter** [comment]
You compiled obs-ftl ? Because then you are missing certain gamecapture files for 32bit games. Look into the regular OBS installdir "under data\obs-plugins\win-capture" and copy all files with a 32 in the name into the obs-ftl fir at the same location

**Comment by luncht1me** [comment]
@Maximilian-Reuter okay, thanks I'll give that a shot tonight! What you've said makes sense, I just didn't realize some of the 32bit files wouldn't compile. 

I'll let you know if it works out. :) :+1:

**Comment by sslivins** [comment]
@luncht1me @Maximilian-Reuter  there is a build script in the build_script folder that will build all 32bit, 64bit and the msi installer, just run "build all " from inside that folder on a clean checkout and you should be good to assuming you have the dependencies installed.  if you run into trouble let me know

**Comment by luncht1me** [comment]
Oh wonderful I copied obs stuff over and it works but I'll run build all

**Comment by Maximilian-Reuter** [comment]
@sslivins I think this can be closed ?

**Comment by luncht1me** [comment]
I think it can the build all script was flawless

**Comment by sslivins** [comment]
glad to hear it @luncht1me closing....
