### ISSUE TITLE
Static libraries in linux packages

### ISSUE THREAD

**Issue by tobiasschulz** [WatchBeam/obs-studio-ftl#22]
Hi,

The .deb package shouldn't contain static libraries. The total uncompressed size of the package is 281 MB and 213 MB are useless static (*.a) ffmpeg libraries. Only the .so files are needed.

1.7M	/opt/obsftl/lib/libavdevice.a
2.4M	/opt/obsftl/lib/libavutil.a
16M	/opt/obsftl/lib/libavfilter.a
140M	/opt/obsftl/lib/libavcodec.a
44M	/opt/obsftl/lib/libavformat.a
6.7M	/opt/obsftl/lib/libswscale.a
2.8M	/opt/obsftl/lib/libopus.a
648K	/opt/obsftl/lib/libswresample.a
213M	total

They should be deleted in the build scriptbefore they are packaged (or excluded by fpm if that's possible).

**Comment by sslivins** [comment]
alright, updated deb and rpm scripts to exclude static libraries, and updated release page.  thanks for point that out @tobiasschulz
