### ISSUE TITLE
Update URL directs to wrong repository

### ISSUE THREAD

**Issue by Scrxtchy** [WatchBeam/obs-studio-ftl#24]
The log file outputs this
`00:36:11.387: [ftl-services plugin] Remote update of URL "https://github.com/WatchBeam/abandoned-ftl-studio/package.json" failed: The requested URL returned error: 404 Not Found`
I was unable to find any relevant information to help when looking through the source code for this repo to fix this

**Comment by Maximilian-Reuter** [comment]
This has already been addressed in https://github.com/WatchBeam/obs-studio-ftl/commit/fa39a5262385485f4ef9f1d669f2161ffc6559e4

**Comment by Scrxtchy** [comment]
Thanks
![](http://orig15.deviantart.net/6ad3/f/2010/291/6/9/facedesk_by_eys123-d3120y1.png)

**Comment by sslivins** [comment]
no worries!
