### ISSUE TITLE
Weird Screens when streaming

### ISSUE THREAD

**Issue by Optionalnickel4** [WatchBeam/obs-studio-ftl#25]
So I decided to test out the new OBS Studio FTL client. But it seems when I start streaming I get weird glitchy screens while streaming. 
![issues](https://cloud.githubusercontent.com/assets/19656872/19558444/88fd8974-9698-11e6-8384-b24a3ca1c1f3.png)

**Comment by Maximilian-Reuter** [comment]
Hey ;) Could you please add your Log so we can see your settings ? It's really hard to guess what's the problem without it. You can find the log by going into OBS, then click on Help->Log Files->Upload Current Log File and then post the link here.

Thanks !

**Comment by sslivins** [comment]
@Optionalnickel4 do you have logs when this occurred?

**Comment by Sataana** [comment]
My guess would be that this is when someone that is forced to Flash is looking at the stream.
I've experienced this aswell, but only when looking at FTL streams in Flash.

**Comment by Maximilian-Reuter** [comment]
yeah flash streams with ftl are completely unusable

**Comment by JimmyMac3** [comment]
Been seeing this weird screen flicker on FTL streams including mine since the upgrade and change of setting to the recommended ones in OBS-FTL.13  every 3 to 5 seconds the screen will go blocky blurry (best way to describe it) I along with some help from others have found the settings that stop it from happening
If you set OBS-FTL.13 like this it will not have the problem
https://gyazo.com/9d0d74a5c37b1b46c55f667d12df106c

**Comment by sslivins** [comment]
yes, ive been tuning the i frame size to help with stream delay, i was a bit aggressive with the settings.  I will probably turn it off next week once i have some more time to tune things but in the meantime you can disable this on your version if you go into %appdata%\obs-studio\plugin_config\ftl-services\services.json and at the very bottom change "x264opts" to "scenecut=0" removing the "ipratio=0.3 ratetol=10" options.  also disabling the custom buffer size or settings it to a higher value will reduce the pulsing effect

**Comment by Optionalnickel4** [comment]
Sorry guys i have the logs i just havent been around my pc. Im currently in the hospital with a friend. Logs will be uploaded Mon or Tues.

**Comment by Optionalnickel4** [comment]
https://gist.github.com/d8989d1976c8a40647d9c71625d0cfb2

**Comment by Maximilian-Reuter** [comment]
Hey ;) Is that a log of you streaming ? Cause it looks like it's a log after startup without streaming.

**Comment by Optionalnickel4** [comment]
http://paste.ee/p/x11V3

**Comment by sslivins** [comment]
you're getting significant packet loss, if you try the latest version it has a speed test built in, can you try that out and send the logs again

**Comment by Optionalnickel4** [comment]
https://gist.github.com/cf7d0454928d512049ec162caf506c4f

**Comment by QuinnDamerell-MS** [comment]
Please open this again if you're still seeing issues with OBS 18.0.1.
