### ISSUE TITLE
'Start Streaming' button not working when setting Stream Type to Beam FTL Service

### ISSUE THREAD

**Issue by theredchord** [WatchBeam/obs-studio-ftl#28]
I've tried to enable FTL w/ both OBS 0.16.2-ftl.14.pre and ftl.13 to no avail. When I set "Stream Type" to "Beam FTL Service", use an appropriate server (either Auto or a specified selection), and set my "Stream Key", then click the "Start Streaming" button, nothing happens and the program doesn't throw any exceptions.

But if I set "Stream Type" to "Streaming Services" and select "beam.pro", the "Start Streaming" button works just fine and the stream launches and operates normally.

Log File Upload: https://gist.github.com/087b6a6ac78c600b534ec49e287a3d05

**Comment by sorryaboutyourcats** [comment]
Could you try switching your audio to 48khz - then restart OBS and try again?

**Comment by Maximilian-Reuter** [comment]
@theredchord yeah it's definitely the audio sample rate.... I mean it's literally written in caps on the release page ;)

**Comment by theredchord** [comment]
@sorryaboutyourcats @Maximilian-Reuter Yes, that worked, thanks!

**Comment by NOKYARD** [comment]
Exact same issue, but my audio is 48khz. 
"Start Recording" works fine, but the stream does not show (You are offline) on my Beam.pro page.
Log File Upload:  https://gist.github.com/b93455a64b1e776c63ad046295234f54

**Comment by sorryaboutyourcats** [comment]
@NOKYARD Please try the settings that I use for OBS-FTL, which can be found [here](http://www.sorryaboutyourcats.wtf/wp-content/uploads/2016/10/TqszsUAB.jpg).

**Comment by NOKYARD** [comment]
I have tried similar settings, and dozens of variations. Still no luck. 
https://gist.github.com/dd8cce540a5f98b9a1500afeae3d8860

Will try lowering the resolution of the cap card next, but i prefer 1080p for uploading to youtube.

**Comment by NOKYARD** [comment]
Is it normal for obs64.exe to be running an hour after exiting the program? 
https://flic.kr/p/MQN1Pj

**Comment by Maximilian-Reuter** [comment]
Did you try multiple ingests ? I had a similar problem when one of the ingests wasn't available

**Comment by NOKYARD** [comment]
I tried Toronto, Seattle and Washington DC. Re-installed 3 times.
https://gist.github.com/ab7e73e12930db410289b3b451527bdb

Also, pressing the "Stop Streaming" button still results in the program never recovering from the "Stopping Stream" phase. Hours after exiting the program there are still one or more instances of it running. 
https://flic.kr/p/NQ598p

**Comment by JimmyMac3** [comment]
Maybe doing a clean reinstall will help - 
1 - Uninstall Current version of OBS-FTL
2 - Make a backup copy of the %appdata%\obs-studio\basic folder (This is a backup of your scenes)
*NOTE* don't backup any of the other folders other than the ones in basic
3 - Delete the %appdata%\obs-studio folder completely
4 - Install the latest version of OBS-FTL
5 - Replace %appdata%\obs-studio\basic with the backup from step 2
6 - Launch OBS-FTL 64 and set all the settings as recommended

**Comment by NOKYARD** [comment]
Justin Cross from Beam.pro got back to me. Apparently, you can not Record and Stream at the same time with this build. If you Start Streaming, then press Start Recording, the stream will stop. Unfortunately, this is why i switched from Tachyon in the first place. Will; keep an eye out for an update with the feature turned back on.

Thank you for your assistance.

**Comment by sslivins** [comment]
this is correct @NOKYARD currently OBS is written in such as way that there is only one audio codec at any given time.  the local recording uses AAC however FTL requires OPUS as it is a requirement of webrtc which is used to display the actual stream on the browser.  While this limitation can be overcome is does require a bit of rework which is outside the scope of OBS-FTL at the moment
