### ISSUE TITLE
Crash when starting stream

### ISSUE THREAD

**Issue by xbrownish3** [WatchBeam/obs-studio-ftl#34]
When I hit 'Start Streaming' OBS instantly crashes with the below error. Seems to work fine without the FTL stream key, but with it crashes. I've tried reformatting, reinstalling, deleting the appdata etc etc.

64 bit win7
amd-8350fx

ERROR:
http://i.imgur.com/vSlytC0.png

SETTINGS:
http://i.imgur.com/QxUnikj.png
http://i.imgur.com/c6FHuOo.png
http://i.imgur.com/7r65RAX.png

ERROR LOG:
[2016-11-14 15-08-33.txt](https://github.com/WatchBeam/obs-studio-ftl/files/590452/2016-11-14.15-08-33.txt)

**Comment by sslivins** [comment]
the crash should be fixed in the latest release https://github.com/WatchBeam/obs-studio-ftl/releases/tag/ftl.16  im curious to know if you are able to stream however as the error reported means you arent able to resolve the ips of the ingests which is odd

**Comment by xbrownish3** [comment]
So the crash stopped happening, I can stream WITHOUT FTL. When I put in the FTL key I get this error. http://i.imgur.com/e7NBKkS.png. I have tried different servers and auto. Here's the logs if it helps any.
[2016-11-16 20-55-35.txt](https://github.com/WatchBeam/obs-studio-ftl/files/596371/2016-11-16.20-55-35.txt) Didn't seem to be any crash logs.

**Comment by sslivins** [comment]
would you mind trying this build and sending me the logs again:  https://dl.dropboxusercontent.com/u/20701844/obs-studio-0.16.5-ftl.zoe.msi

**Comment by xbrownish3** [comment]
Same situation as before, here's the log from the above build.
[2016-11-18 22-48-17.txt](https://github.com/WatchBeam/obs-studio-ftl/files/601239/2016-11-18.22-48-17.txt)

**Comment by sslivins** [comment]
thanks @xbrownish3 .  the error im getting this time is a bad or invalid stream key which is not the error from before.  can you verify you have that set correctly?

**Comment by xbrownish3** [comment]
I've reset the key a few different times and it seems to not work each time.

**Comment by sslivins** [comment]
Well this is a parsing error of the key, it's not that the server thinks it's invalid (at least not yet). It's that the ftl library couldn't separate the channel ID (the number part) from the key itself (the random characters part).  At this point you could literally make the key 123-abc and it should at least fail in the same way as previously

**Comment by xbrownish3** [comment]
Hmm, so is there a fix? Or will there need to be a new build?

**Comment by sslivins** [comment]
Can you check your settings, as I said this isn't a bad key, either the stream key field is blank or something else is wrong with how it was input

**Comment by xbrownish3** [comment]
http://i.imgur.com/qM6QtJy.png
I've tried refreshing the stream key, using the same one for a few days etc. Everything else is default besides the below. Only thing I can try now, which my friend suggested is making a new beam.pro accounts and trying it then.
Settings:
http://i.imgur.com/feL3hZe.png
http://i.imgur.com/pkAGZER.png

**Comment by sslivins** [comment]
It works e this time but since you posted a picture of your key I would suggest getting a new one.  Please try this build, Im hoping it will fix the issue https://www.dropbox.com/s/z9tcd47hc7gxnee/obs-studio-0.16.5-ftl.16.ssl.msi?dl=0

**Comment by xbrownish3** [comment]
Getting the same error, tried both of the accounts again using different keys etc. Did full uninstalled/cleared appdata.
[2016-11-20 00-14-40.txt](https://github.com/WatchBeam/obs-studio-ftl/files/601870/2016-11-20.00-14-40.txt)

**Comment by sslivins** [comment]
okay, i did a bit more research and this appears i am using a feature that isnt supported in windows 7, try this version:  https://dl.dropboxusercontent.com/u/20701844/obs-studio-0.16.5-ftl.16.ssl.2.msi

**Comment by sslivins** [comment]
here's the official release which this fix https://github.com/WatchBeam/obs-studio-ftl/releases/tag/ftl.17

**Comment by sslivins** [comment]
i have confirmation the above build fixes this issue
