### ISSUE TITLE
DX 12 Capture Support not enabled

### ISSUE THREAD

**Issue by Maximilian-Reuter** [WatchBeam/obs-studio-ftl#35]
As far as I could discern there seems to be no DX12 capture support compiled into OBS with ftl 16.
In version 0.16.5 DX12  support was added as an additional cmake config.

Any reason for not including it or is it simply an oversight ?

**Comment by sslivins** [comment]
definitely an oversight on my part, thanks for point it out

**Comment by sslivins** [comment]
should be working now in https://github.com/WatchBeam/obs-studio-ftl/releases/tag/ftl.17  i confirmed it was part of the build and the build flag was enabled.  not sure how to utilize it but let me know if you can

**Comment by Maximilian-Reuter** [comment]
Yeah it works now. Thx!
