### ISSUE TITLE
Missing DLLs 0.16.6 with FTL.17

### ISSUE THREAD

**Issue by CAProjects** [WatchBeam/obs-studio-ftl#37]
I installed 0.16.6 with FTL.17 there are missing DLLs

Qt5Core.dll
Qt5Gui.dll
Qt5Widgets.dll

causes the program not to start. This happens for 32 and 64 bit

I had to revert back to 0.16.5 with FTL.16

**Comment by sslivins** [comment]
those files should be located in C:\Program Files (x86)\OBS Studio - FTL\bin\64bit and C:\Program Files (x86)\OBS Studio - FTL\bin\32bit respectively.  can you confirm if they exists in those paths when using .17?

**Comment by Maximilian-Reuter** [comment]
That is an artifact of the installer not correctly installing the new version over the old. 
A second try or a complete uninstall should resolve that...
Not quite sure why this happens though

**Comment by sslivins** [comment]
yeah, i'm curious also, I'm assuming you went from .16 to 17 @CAProjects ?

**Comment by Maximilian-Reuter** [comment]
I had a similar issue when going from 16 to 17 but also had this happening on earlier builds sporadically

**Comment by sslivins** [comment]
yeah, i uninstalled everything, installed .16 then installed .17 and can reproduce the issue.  the QT files are missing...very odd

**Comment by Maximilian-Reuter** [comment]
I just tested it and it seems to be reproducible when going from 16 to 17...
I attached the log from the msi
[log.txt](https://github.com/WatchBeam/obs-studio-ftl/files/602772/log.txt)

**Comment by CAProjects** [comment]
Ok so i just checked this by installing 0.16.6 with FTL.17 again (done this 10) times to make sure

All 10 times it will not install Qt5Core.dll, Qt5Gui.dll, Qt5Widgets.dll but running the installer again and selecting repair will install the 3 files in both 32 and 64 bit.

NOTE: installing 0.16.5 with FTL.16 over 0.16.6 with FTL.17, it installed all files fine 100%. 

2nd NOTE: you must remember that not everyone is tech savy (i am) and this can cause some confusion with others

**Comment by sslivins** [comment]
yeah, i just tried the repair also and it fixes the issue as you mentioned.  i'll have to see what changed in Jim's branch, that was the major difference in this version (going from 0.16.5 to 0.16.6) very little of my code changes so that seems unlikely.  anyhow thanks for pointing this out, it will definitely cause support tickets so im glad to find it early

**Comment by CAProjects** [comment]
I also tested OBS Studio to see if the issue come from there but no, OBS Studio updated from 0.16.5 to 0.16.6 with no isues

**Comment by Maximilian-Reuter** [comment]
I mean all of this only happens because with my pull https://github.com/WatchBeam/obs-studio-ftl/pull/27 I enabled the installer to upgrade the previous version. Before that it didn't let you do that and you had to manually uninstall the previous version before installing the new one.

**Comment by Maximilian-Reuter** [comment]
https://blogs.msdn.microsoft.com/astebner/2015/11/16/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers/ this seems to touch on the issue

**Comment by sslivins** [comment]
ah, that could explain it, i built version .16 on my laptop and version .17 on my desktop...sure enough the image on the right is .16 and the one on the left is .17....let me upgrade my QT and try again....thanks!

**Comment by sslivins** [comment]
alright, it looks good to go, i updated the release and replaced the existing file so just download it again @CAProjects .... thanks again @Maximilian-Reuter

**Comment by CAProjects** [comment]
Works perfectly 

Thanks :)
