### ISSUE TITLE
Missing MSVCP140.dll and VCRUNTIME140.dll

### ISSUE THREAD

**Issue by 30footman** [WatchBeam/obs-studio-ftl#38]
Hey, I was trying to install obs-studio-ftl newest one and I haven't used it ever before. A friend of mine recommended it and when it was finished I tried booting up the app and every time it gives me the error message saying that MSVCP140.dll and VCRUNTIME140.dll are both missing and is preventing it from starting up. I have uninstalled multiple times and reinstalled as well as trying to repair using the installer but nothing seems to work.

**Comment by ibigfire** [comment]
https://support.microsoft.com/en-us/kb/2977003

Getting the latest Visual C++ Redistributable Package should solve your problem for you, I think.

**Comment by 30footman** [comment]
It has fixed it, Thank you.
