### ISSUE TITLE
BrowserSource stops working

### ISSUE THREAD

**Issue by M00CH1E** [WatchBeam/obs-studio-ftl#44]
I have run into an issue where my browser_source plugin stops working and the source disappears until i go into the options screen and OK back out of it to refresh. this is happening constantly. 

I have tried multiple sources and it does it with them all.

This is using FTL.17 and above that i have tried.

UPDATE: OK so there is a new twist to this, i use the browser source with Streamjar for notifications and event list etc. Now my Overlay vanished again, so i did  a Test follower in Streamjar to see if i still got notified and it refreshed the overlay and it showed. Could it be that the browser_source  is shutting down when not active, even though the check box is not ticked?

UPDATE 2: I Have done a full uninstall and reinstall of all copies of OBS Studio/OBS Studio-FTL and this problem is still persisting even now

**Comment by Scrxtchy** [comment]
Should be closed, you have done the right thing and submitted the bug here;
https://obsproject.com/mantis/view.php?id=738

**Comment by QuinnDamerell** [comment]
I believe this should be resolved with the newest update. If not please reopen. :)

**Comment by Scrxtchy** [comment]
You Magical Maniac :+1:
