### ISSUE TITLE
Need separate settings for regular OBS and OBS FTL

### ISSUE THREAD

**Issue by Saiasanc** [WatchBeam/obs-studio-ftl#47]
So I just started streaming to both Twitch and Beam separately (meaning not at the same time). To do so and still use FTL on Beam, I have to have both the regular OBS and OBS FTL installed. But when I make changes in regular OBS to the Stream settings to accommodate Twitch and then later switch to OBS FTL for Beam, the settings are all out of whack and I have to go to Beam to get my Stream Key again.

You all should really have this other instance of OBS FTL use it's own separate settings instead of reading what is in there for regular OBS.  At least until such time as FTL is integrated permanently into OBS Studio.

**Comment by dontbbad** [comment]
Agreed, FTL specific settings would be nice.

**Comment by Maximilian-Reuter** [comment]
Simple and quick solution: multiple profiles

**Comment by dontbbad** [comment]
Does that work? Awesome ill have to give that a try.

**Comment by Saiasanc** [comment]
Herp-a-derp. I should have thought of that. Thank you @Maximilian-Reuter for reminding me that was an option!  As far as I am concerned, this issue can be closed. :)
