### ISSUE TITLE
Windows capture

### ISSUE THREAD

**Issue by JimmyMac3** [WatchBeam/obs-studio-ftl#48]
I am trying to win cap a chrome browser window and it captures the correct size but it is just a black box not the actual window. I installed regular OBS-Studio and had the exact same result. the name of the source in the log file is Minecraft

[2016-12-22 08-11-22.txt](https://github.com/WatchBeam/obs-studio-ftl/files/669243/2016-12-22.08-11-22.txt)

**Comment by sslivins** [comment]
you'll need to disable hardware acceleration in chrome for window capture to work.  go into the settings and under advanced settings uncheck the 'use hardware acceleration when available..."  http://prntscr.com/dmp0ry

**Comment by JimmyMac3** [comment]
Thanks so much that work perfect!
