### ISSUE TITLE
Platform-dependent functions errors when compiling on macOS 10.12.1

### ISSUE THREAD

**Issue by justin97530** [WatchBeam/obs-studio-ftl#54]
In `obs-studio-ftl/plugins/obs-outputs/ftl-stream.c`, two functions are not available:
- Ln 1082: implicit declaration of function 'strncpy_s' is invalid in C99
- Ln 1146: implicit declaration of function '_snprintf_s' is invalid in C99

These two are the only errors that prevent a successful compilation on macOS (latest commit: b9dda66, branch: ftl).

**Comment by sslivins** [comment]
thanks for pointing this out:  fixed here: 642760bd7f392aefd5e83eab2360bf1b43b51e04
