### ISSUE TITLE
Recent OBS+FTL.27 and FTL.28 Crashes on Win10. Fine on OBS Studio 17 Standard

### ISSUE THREAD

**Issue by theredchord** [WatchBeam/obs-studio-ftl#57]
Hi, I've been having great experience w/ all the OBS+FTL builds thus far, but recently had a string of crashes associated w/ builds FTL 27 and 28 (mostly 28) while using RTMP, but didn't have the chance upload logs for my issues w/ 28, due to complete BSOD or freezes.

I originally got the first crashes from FTL 28 and uninstalled and installed FTL 27 (no prior crashes before today, but had 1 crash after uninstalling FTL 28)

I did upload a log for 27, though: https://gist.github.com/anonymous/45e7497c4e49b62e08f9565d03aa382f

I was playing Nuclear Throne (lots of crashes) and BattleBlock Theater (1 crash on FTL 27).

I just switched to the newest build of standard OBS Studio 17.0 and didn't experience any crashes with the same games on RTMP.

**Comment by Maximilian-Reuter** [comment]
very weird.. as the core code for rtmp streaming should be pretty much the same... do you have any crash logs ? They are under "C:\Users\YOURUSERNAME\AppData\Roaming\obs-studio\crashes".
You should also find partial logs (because of bsod) in "C:\Users\YOURUSERNAME\AppData\Roaming\obs-studio\logs". Otherwise there isn't a whole lot that can be done.

**Comment by theredchord** [comment]
@Maximilian-Reuter I found 3 crash logs and they all say the following:

Failed to recreate D3D11: Failed to duplicate output (80070005)

Here is one of my logs while playing Nuclear Throne:

[2017-01-17 21-52-44.txt](https://github.com/WatchBeam/obs-studio-ftl/files/714756/2017-01-17.21-52-44.txt)

**Comment by Maximilian-Reuter** [comment]
could you also provide a crash log ?

**Comment by theredchord** [comment]
@Maximilian-Reuter All the crash logs just say: Failed to recreate D3D11: Failed to duplicate output (80070005)
[Crash 2017-01-17 21-54-46.txt](https://github.com/WatchBeam/obs-studio-ftl/files/715107/Crash.2017-01-17.21-54-46.txt)
[Crash 2017-01-17 21-59-58.txt](https://github.com/WatchBeam/obs-studio-ftl/files/715108/Crash.2017-01-17.21-59-58.txt)
[Crash 2017-01-17 22-38-48.txt](https://github.com/WatchBeam/obs-studio-ftl/files/715106/Crash.2017-01-17.22-38-48.txt)

**Comment by Maximilian-Reuter** [comment]
just out of curiosity, does this also happen with ftl streaming ?

**Comment by theredchord** [comment]
I haven't tried FTL yet, but I can give it a shot tonight and post any crash logs.

**Comment by theredchord** [comment]
I just had a crash with FTL just now. Here's the crash log:

[Crash 2017-01-18 19-34-22.txt](https://github.com/WatchBeam/obs-studio-ftl/files/715483/Crash.2017-01-18.19-34-22.txt)

**Comment by Maximilian-Reuter** [comment]
and you tried this with obs 17.0 and it didn't crash ?

**Comment by theredchord** [comment]
@Maximilian-Reuter Just played OBS Studio 17.0 w/ Nuclear Throne last night and experienced a crash. It looks like it may be a problem w/ the core OBS app and the game.
