### ISSUE TITLE
Crash upon installation, Errorcode 2503 + 2502

### ISSUE THREAD

**Issue by BluSunrize** [WatchBeam/obs-studio-ftl#58]
Heya!

I seem to run into issues installing the software. I've tried versions 27 and 28, both of fail to install, presenting the errorcode 2503 followed by 2502:
http://puu.sh/tqXp8/6974e36013.png
http://puu.sh/tqXxq/b7dd82d701.png

The setup then ends prematurely, informing me that no modifications to the system were made, due to the failed installation.
This is on Windows 10, 64bit, i7-4770 CPU, 16GB Ram.
I have attempted the use of admin mode when executing the installer, to no apparent changes.

**Comment by sslivins** [comment]
it seems unusual that both would fail, would you mind trying 30 which i uploaded last night

**Comment by BluSunrize** [comment]
I'm afraid the issue persists, as do the error codes.
I shouldn't need anything but the msi file to install the software, should I?
Could an old OBS install interfere with this?

**Comment by Maximilian-Reuter** [comment]
as with #59 there seems to be an issue with your windows installer. In order to try and find the issue causing this you can try creating an installation log by using this commandline instruction:
 `msiexec /i "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"`
 If you could post the log here afterwards we could try and look for an issue.

**Comment by BluSunrize** [comment]
Here you go:
https://gist.github.com/BluSunrize/584794500311810df36fec2718157635

Btw. when recommending that command to someone, you'll have to tell them to create that log file first, otherwise it refuses to work.
Ran the setup without modifying the install path or anything, as well, btw. Fully default install.

**Comment by Maximilian-Reuter** [comment]
Thanks ;) Found something that might help: https://answers.microsoft.com/en-us/windows/forum/windows_vista-windows_programs/error-2503-called-runscript-when-not-marked-in/76e72d98-cbef-432f-8f6f-40417d139bc1

**Comment by BluSunrize** [comment]
Yeah, giving all permissions to my useraccount for Windows/Temp apparently did it.
I'm shocked that something like this is necessary though. Not sure if that's something you folks can fix on your side, or if that'S just MS being akward.

**Comment by Maximilian-Reuter** [comment]
I think that is just part of msi... glad it worked out though

**Comment by Maximilian-Reuter** [comment]
@BluSunrize you should be able to close the issue yourself
