### ISSUE TITLE
OBS-Studio 17.0.0 with FTL.28

### ISSUE THREAD

**Issue by SingingTurnip** [WatchBeam/obs-studio-ftl#59]
I have downloaded the latest build and after double-clicking the .msi file there is the little Windows 10 loading thing by the mouse pointer but that is all that happens. 

I have watched it for 10 minutes, I have disabled UAC and I cannot run as admin as that option is not available if I right click the icon.

The only way to get out of it is by restarting my system as it doesnt show in Task Manager, normal OBS Studio 17.0.2 loads fine, but it's FTL that I want to use.

**Comment by sslivins** [comment]
i have not heard other reports of this as of yet but i just updated to 17.0.2, give that a shot and let me know

**Comment by SingingTurnip** [comment]
Normal OBS Studio is fone, it's just this FTL version that is not working. I have updated it to FTL.30 and still got the issue.

**Comment by Maximilian-Reuter** [comment]
You must've somehow gotten your windows installer borked... anyways this program http://lessmsi.activescott.com/ lets you extract the contents of the msi which you then should be able to run without problems. I would recommend you though to look if you have this issue with other msi files.

**Comment by SingingTurnip** [comment]
Sorry but I've fixed it, I replied about a different issue all together...

I had to disable Windows SmartScreen or whatever's it's called to install it.

The issue I have now is that it doesn't work with H1Z1 KOTK.

**Comment by Maximilian-Reuter** [comment]
@SingingTurnip  since u already posted this in https://github.com/WatchBeam/obs-studio-ftl/issues/42 I don't see any reason why this issue should remain open ?
