### ISSUE TITLE
Recording Error on Windows 10

### ISSUE THREAD

**Issue by ubermentat** [WatchBeam/obs-studio-ftl#67]
OBS-FTL Version: 18.0.1-ftl0.9
Windows 10: most recent update
Error: When I hit the "Start Recording" button, I get an error message that reads "Starting the output failed. Please check the log for details. Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date."

I would check the log, but I'm not 100% sure where to find it.

The recording feature works fine with normal OBS.

**Comment by QuinnDamerell-MS** [comment]
Recording isn't currently supported in this version of OBS. Sorry. :(
