### ISSUE TITLE
GPU supported by Studio but not by FTL? 

### ISSUE THREAD

**Issue by OneHighAce** [WatchBeam/obs-studio-ftl#70]
Hi there. I've recently been tinkering with OBS Studio FTL and really like it, the only problem is there is no option to use my gpu encoder there is only the x264 option. When I use normal OBS Studio my AMD encoder shows up as an option but not with FTL. My cpu is only an I5 so I need the help of my graphics card or i end up getting a huge delay, which defeats the entire purpose of using ftl. If anyone knows what the issue might be I would be eternally grateful!

**Comment by Maximilian-Reuter** [comment]
I'm not sure exactly but I'd guess that OBS-FTL isn't built with the AMD encoder included.
Do you by any chance have a mainboard with iGPU support ? cause if you do you should be able to use Quicksync if correctly configured

**Comment by QuinnDamerell-MS** [comment]
We currently don't support AMD encode. Sorry!
