### ISSUE TITLE
Video Issues Using OBS 18.0.1 with FTL .0.9.2

### ISSUE THREAD

**Issue by TexasTeaMan** [WatchBeam/obs-studio-ftl#72]
So basically the latest update the audio/video sync has been fixed but now my video is kinda jacked up. Here is the link so you can see what I am talking about:

[Video Issues at 4min mark](https://beam.pro/VapinGamers?vod=1172490)

I have had multiple people complain to me about this issue and after watching the playback I am frustrated. How do I fix this? Any ideas? Thanks

**Comment by QuinnDamerell** [comment]
Were you see these issues the video issues with the last version of ftl?

**Comment by Saiasanc** [comment]
So it seems to me like you have two copies of the same source playing at the same time. It's causing both video AND audio ghosting for the gameplay.  Which could present as video "jittering". This could be your capture card (I assume that's what you are using since it is obvious you are streaming a playstation game).  The first thing I would recommend is completely removing your video capture source, shutting down OBS and then re-adding it. Sometimes that works. But it really depends on the capture device.

**Comment by TexasTeaMan** [comment]
@QuinnDamerell I am using the most up to date verison of FTL for OBS.

@Saiasanc I will have to try that and see. The problem is that if I use regular OBS it works just fine, its only with FTL version that I am running into these issues.

**Comment by TexasTeaMan** [comment]
Ok did what you all suggested, changed some additional settings and still got the issue. I am wondering if it has to do with Nivida GPU. Here is the latest stream test

[Video Issues 3-12-2017](https://beam.pro/VapinGamers?vod=1183647)

Anyhelp guys is very much appreciated. Should I attach or show the log file? Please let me know. Thanks

**Comment by Maximilian-Reuter** [comment]
@TexasTeaMan you should always attach log files when talking about issues :D

**Comment by TexasTeaMan** [comment]
@Maximilian-Reuter thanks for the response as typically I would if asked. Sometimes it is easier to post the issue if someone in the community has already done a work around. 

[2017-03-12 01-27-52.txt Log File](https://github.com/WatchBeam/obs-studio-ftl/files/836660/2017-03-12.01-27-52.txt)

I am attaching the recent log file from the test stream I did last night. I really appreciate all of your time and I am sure I must be missing something. I am begging to suspect its the Nvidia GPU that is causing the issue.

**Comment by Maximilian-Reuter** [comment]
@TexasTeaMan ah now we're talkin' ! Could you try setting B frames to 0 in the advanced encoder options ?
Last time I tried using Nvenc B frames kinda screwed with my output too. Alternatively, if your MB supports integrated GPUs you should be able to use Quicksync which should give you comparable performance.

**Comment by TexasTeaMan** [comment]
Ok thanks @Maximilian-Reuter! I will try that here in a little bit and i will post the results. The benchmarks I have seen using Quicksync though are not good but I will try it out and let you know. I would if at all possible would rather use Nvenc but at this point if I can get it to work well with ftl I would be happy.

**Comment by Maximilian-Reuter** [comment]
@TexasTeaMan  I've been using Quicksync for about 2 years now without any issues and am mainly using it since it doesn't impact my FPS which Nvenc does because it uses GPU resources that I then can't use for my game.

**Comment by TexasTeaMan** [comment]
@Maximilian-Reuter Thanks and that was the ticket. Although if I stream at 1080p 60fps I got lots of frame drops on the video for some reason. Once I lowered the bit rate to 720p 60fps it looks so much better and is relatively smooth. I even tried it at 1 and it was slightly off giving some people eye strain. Really weird.
