### ISSUE TITLE
Stream locks up and bitrate indicator in OBS-FTL says 124.

### ISSUE THREAD

**Issue by StrikerMan780** [WatchBeam/obs-studio-ftl#73]
Seems on occasion, after streaming for a little while, the stream will lock up. Beam will still show it as live, but the image is frozen, and OBS-FTL says the bitrate is extremely low (100-200kbps). Stopping and starting the stream again will fix it, but this shouldn't be happening in the first place.

My settings are as follows:
NVENC H.264
Rate Control: CBR
Bitrate: 5000
Keyframe Interval: 1
Preset: High Quality
Profile: High
Level: Auto
Two-Pass Encoding: On
B-Frames: 0

**Comment by MatthewM** [comment]
I have this issue as well and have submitted a ticket to beam on this. I'll attach the log here as well.

Encoder Settings:
Video: 720p30
Encoder: x264
Rate Control: CBR
Bitrate: 2200
Keyframe: 3
CPU Preset: Fast
Profile: High
tune: zerolatency
No extra options
[Log file](https://github.com/WatchBeam/obs-studio-ftl/files/852832/2017-03-18.18-50-17.txt)

**Comment by Maximilian-Reuter** [comment]
I can definitely second that. With the new OBS-FTL version this happens quite regularly. Doesn't happen with OBS 17.0.2-ftl.32

**Comment by QuinnDamerell** [comment]
Thanks for the reports, I will fix the issue ASAP and for now am going to pull this version of OBS. Please feel free to jump back a version to prevent this issue.

**Comment by QuinnDamerell** [comment]
Additionally​, if anyone is able to report this under the debugger I would appreciate a debug dump or stack trace of the threads.

**Comment by MatthewM** [comment]
The prior version seems to be working fine. Have a 1.5hr+ stream going that normally would have taken 20 minutes or so to freeze.

**Comment by QuinnDamerell-MS** [comment]
Resolved in 0.9.4
