### ISSUE TITLE
 upon install: Missing MSVCD140.DLL and VCRUNTIME140.DLL

### ISSUE THREAD

**Issue by proofsinpuddin** [WatchBeam/obs-studio-ftl#74]
Hello, when I download and install, I go to open the program, and it states twice I am missing both MSVCD140.DLL  and  VCRUNTIME140.DLL 

I tried doing a uninstall and reinstall as requested by the message but still the same issue.
If there is already a fix for this I apologize but I did not see it when searching through the forums.

Thanks in advance!

**Comment by Maximilian-Reuter** [comment]
install this in both x86 and x64 version : https://www.microsoft.com/en-gb/download/details.aspx?id=48145

**Comment by proofsinpuddin** [comment]
Awesome! thanks so much @Maximilian-Reuter . it is now working!
