### ISSUE TITLE
Full Installer for OBS Studio with FTL 0.9.2 

### ISSUE THREAD

**Issue by gofirst2220** [WatchBeam/obs-studio-ftl#75]
I saw that you have a update but how do I install/replace the OBS Studio with FTL 0.9.0 version with the FTL 0.9.2 version?

**Comment by QuinnDamerell-MS** [comment]
There's a known issue with 0.9.2 so we took it down, but we should be putting a new version up shortly. :)

Once it's up you can run the new installer over the existing install and it will do everything correctly.
