### ISSUE TITLE
Cant see anything on preview

### ISSUE THREAD

**Issue by jakemobile34** [WatchBeam/obs-studio-ftl#79]
I cant see anything on my preview, ive tried everything i can. idk why but i had the same exact setup on another computer and it recorded just fine, but now on my main PC its just drawing a blank. heres the log of one of the latest attempts, FYI everything is up to date
[2017-03-26 07-09-00.txt](https://github.com/WatchBeam/obs-studio-ftl/files/870473/2017-03-26.07-09-00.txt)

**Comment by Maximilian-Reuter** [comment]
"could not open process" usually means ure trying to capture an elevated process with a non elevated obs.

**Comment by jakemobile34** [comment]
so.... run obs with admin?

**Comment by Maximilian-Reuter** [comment]
if you think that suffices as solution i'd suggest closing the issue
